version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

    networks:
      - db
networks:
  db:
    driver: host